In [6]:
import numpy as np

list_ = [ '1' , '2', '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [7]:
list_

['1', '2', '3', '4', '5']

In [8]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

###
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [19]:
### Yes, there is difference in data types of both the variables.See in the example below
print(type(list_))
print(type(array_list))
#list_ is a list while array_list is a numpy array.

<class 'list'>
<class 'numpy.ndarray'>


###
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [21]:
list_

['1', '2', '3', '4', '5']

In [22]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [23]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [24]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


###
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [28]:
array_list = np.array(object = list_, dtype = int)

In [29]:
array_list

array([1, 2, 3, 4, 5])

In [31]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [32]:
list_

['1', '2', '3', '4', '5']

In [33]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [34]:
## Yes data type of array_list got changed from  'numpy.str_' to 'numpy.int64' but there is no change in list_ elements data type.

###
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [35]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [36]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# For shape
shape = np.shape(num_array)
print(shape)

(2, 3)


In [40]:
# for size
size = np.size(num_array)
print(size)

6


###
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [47]:
null_array = np.zeros((3,3))
null_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [49]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
